### ISSUE TITLE
Border/titlebar theme for sub-windows in Windows 10 looks wrong/old

### ISSUE THREAD

**Issue by vitaminj** [Microsoft/winfile#12]
This issue can be insta-closed by the maintainer, just a placeholder to indicate this is a known Windows 10 problem and can be voted on here: https://aka.ms/Bjiosw

**Comment by craigwi** [comment]
Thanks.  I up voted the feedback too!

**Comment by keithzg** [comment]
I voted too; I immediately went searching for such an issue here once I opened up WinFile and noticed that it has the same MDI theming issue that annoys me about one of our programs at my day job!

Unfortunately that link is not available on the public web, so I figured I should make this more public statement that the tantalizing and annoying fact of this is, this //was// fixed at one point and the styling was updated! I'll demonstrate using WinFile:

![winfile_server2012r2](https://user-images.githubusercontent.com/3020724/38588878-455bb3fe-3ce5-11e8-805b-43392a2ac618.png)

Well hey, the base window coloration is still the default Vista-era one, but the shape and button styling looks right! That's on Windows Server 2012 R2 (contemporary to Windows 8.1); it also looks fine on Server 2012 (contemporary to Windows 8).

Sadly, as of Server 2016 (IIRC ~TP3? The early technical previews were still fine), the desktop branch seems to have been merged back in overtop of the newer styling:

![winfile_server2016](https://user-images.githubusercontent.com/3020724/38588935-95b2281a-3ce5-11e8-92c9-c9f508f78835.png)

So alas, at some point this seemed to be in the process of getting better, but that seems to have been discarded, whether deliberately or through accident/byproduct of the Win10 merge.

**Comment by ZanderBrown** [comment]
I know MDI is essentially dead from Microsofts perspective but quite a few of there own applications still use it (esp in administration) and it just seems silly this is still an issue

Without knowing the codebase I can't imagine this would be too hard, after all it was successfully updated for XP (complete with Visual Styles support) and then again for Vista

All we can do is wait and see if MS decides to fix this (and upvote the feedback)
